Repository hajkmap/Hajk, pull requests merged in 2022-09, with the labels that each got.

#1157 Bookmark Removal Confirmation
  new-client/src/components/ConfirmationDialog.js
  new-client/src/plugins/Bookmarks/BookmarksView.js
  new-client/src/plugins/Sketch/views/SaveView.js
Labels: new-feature

#1166 Feature/1160 sketch replace warning
  new-client/src/plugins/Sketch/views/SaveView.js
Labels: new-feature

#1168 feature/1143 analytics matomo
  backend/MapService.Tests/MapService.Tests.csproj
  backend/MapService.Tests/app.config
  backend/mapservice/Models/MapConfig.cs
  backend/mapservice/Web.config
  backend/mapservice/mapservice.csproj
  new-client/src/models/Analytics.js
  new-client/src/models/SearchModel.js
Labels: new-feature

#1169 Fix automatic zoom on mobile devices
  new-client/public/index.html
Labels: bug

#1173 Feature/1093 new dummy plugin
  new-client/src/components/App.js
  new-client/src/models/DrawModel.js
  new-client/src/plugins/Dummy/Dummy.js
  new-client/src/plugins/Dummy/DummyModel.js
  new-client/src/plugins/Dummy/DummyView.js
  new-client/src/plugins/Dummy/constants/index.js
Labels: module:client/plugin

#1175 Added a plugin-template
  new-client/src/plugins/Template/Template.js
  new-client/src/plugins/Template/TemplateView.js
Labels: new-feature

#1180 Feature/1171 plugin history
  backend/mapservice/App_Data/map_1.json
  backend/mapservice/Models/MapSetting.cs
  new-admin/src/views/mapoptions.jsx
  new-backend/App_Data/map_1.json
  new-client/public/simpleMapConfig.json
  new-client/src/components/App.js
  new-client/src/controls/RecentlyUsedPlugins.js
  new-client/src/models/AppModel.js
  new-client/src/plugins/BaseWindowPlugin.js
  new-client/src/plugins/DialogWindowPlugin.js
Labels: module:client/core, new-feature

#1189 Fix/1181 cyrillic print support
  new-client/src/plugins/Print/PrintModel.js
  new-client/src/plugins/Print/constants/index.js
  new-client/src/plugins/Print/constants/roboto-normal.js
Labels: module:client/plugin

#1190 Potential fix for #1186
  new-client/src/models/DrawModel.js
Labels: module:client/plugin

#1192 Feature/1191 placement warning
  new-client/src/plugins/Print/AdvancedOptions.js
Labels: new-feature
